export const FETCH_LIST = 'FETCH_LIST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED'

export const ADD_MUSIC = 'ADD_MUSIC'
export const ADD_MUSIC_SUCCESS = 'ADD_MUSIC_SUCCESS'
export const ADD_MUSIC_FAILED = 'ADD_MUSIC_FAILED'

export const DELETE_MUSIC = 'DELETE_MUSIC'
export const DELETE_MUSIC_SUCCESS = 'DELETE_MUSIC_SUCCESS'
export const DELETE_MUSIC_FAILED = 'DELETE_MUSIC_FAILED'

export const FILTER_MUSIC = 'FILTER_MUSIC'
export const FILTER_MUSIC_SUCCESS = 'FILTER_MUSIC_SUCCESS'

